// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tubpnlfpxrsorwaparts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YnBubGZweHJzb3J3YXBhcnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mzk0NTAsImV4cCI6MjA2NDAxNTQ1MH0.bFkcvOwIKs1sDys2Ca-Qe266JuPI5fr964Tyj_mwX6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);